data_dir: "data/testing/Bern"
output_dir: "results/testing"
output_suffixe: "Bern_b0_dataset_CAS_2500_50epochs"
model_dir: results/training/segformer_output_50_epochs
save_mask_as_img: True
save_preds_lbls: True
num_samples_per_buffer: 1000  # if save_preds_lbls = True