output_dir: "results/training"
output_suffixe: Longxi_Bern_v2_focal_dice_losses
# output_suffixe: test
# output_suffixe: Bern_v2_focal_dice_losses
val_split: 0.1
num_epochs: 50
batch_size: 8
num_workers: 2
learning_rate: 5e-5
weight_decay: 0.01

from_pretrain: False
pretrain_dir: results/training/segformer_output_50_epochs
resume_from_existing: False
existing_dir: results/training/20251217_154136_2_epochs_Bern_v2_da_splitsets

do_data_augmentation: True

pretrained_model: nvidia/segformer-b0-finetuned-ade-512-512
# save_preds_lbls: True


# list of pretrained models:
# nvidia/segformer-b0-finetuned-ade-512-512
# nvidia/segformer-b0-finetuned-cityscapes-1024-1024
# nvidia/segformer-b0-finetuned-cityscapes-512-1024
# nvidia/segformer-b0-finetuned-cityscapes-640-1280
# nvidia/segformer-b0-finetuned-cityscapes-768-768
# nvidia/segformer-b1-finetuned-ade-512-512
# nvidia/segformer-b1-finetuned-cityscapes-1024-1024
# lsi55/ddpm-ema-nvidia-segformer-b1-finetuned-cityscapes-1024-1024
# nvidia/segformer-b2-finetuned-cityscapes-1024-1024
# nvidia/segformer-b2-finetuned-ade-512-512
# nvidia/segformer-b3-finetuned-ade-512-512
# nvidia/segformer-b3-finetuned-cityscapes-1024-1024
# nvidia/segformer-b4-finetuned-ade-512-512
# nvidia/segformer-b4-finetuned-cityscapes-1024-1024
# nvidia/segformer-b5-finetuned-ade-640-640
# nvidia/segformer-b5-finetuned-cityscapes-1024-1024
# janakipanneerselvam/SegFormer_Sunlit_nvidia_mit-b5
# janakipanneerselvam/SegFormer_Sunlit_nvidia_mit-b5_v2
# janakipanneerselvam/SegFormer_Sunlit_nvidia_mit-b5_Almonds
# janakipanneerselvam/Almond_SegFormer_Sunlit_nvidia_mit-b5